const modules={Inicio:{icon:"🏠"}, "Mis Fincas":{icon:"🌿",desc:"Gestión de fincas generadoras"},"Mapa":{icon:"📍",desc:"Ubicaciones y puntos de recolección"},"Rutas":{icon:"🚛",desc:"Programar y hacer seguimiento"},"Punto de Acopio":{icon:"⚖️",desc:"Recepción y pesaje de biomasa"},"Trazabilidad":{icon:"🔍",desc:"Historial completo por lote"},"Transformación":{icon:"⚗️",desc:"Maduración, laboratorio y ensacado"},"Despacho":{icon:"📦",desc:"Salida y comercialización de abono"},"Reportes":{icon:"📊",desc:"Indicadores ambientales y económicos"}};
const rf={"Mis Fincas":"RF1","Mapa":"RF1","Rutas":"RF2","Punto de Acopio":"RF3","Transformación":"RF4","Trazabilidad":"RF5","Despacho":"RF6","Reportes":"RF7"};
const activities=[["09:41","Lote L-2026-095 recolectado en Finca El Progreso"],["08:15","Ruta R-02 en curso — Camión KLM-891 hacia Apartadó"],["Ayer","Análisis de laboratorio en proceso para lote L-2026-093"],["Ayer","Despacho completado — Lote L-2026-091, 2.400 kg → Coop. Banacol"]];
const content=document.getElementById("pageContent");
function home(){content.innerHTML='<div class="eyebrow">🏠 Inicio</div><h1 class="title">Bienvenido, yola</h1><p class="muted">Coordinador de planta · viernes, 2 de octubre de 2026</p><div class="stats"><div class="stat"><span>Fincas activas</span><strong>4</strong></div><div class="stat"><span>Biomasa este mes</span><strong>11.15 t</strong></div><div class="stat"><span>Lotes en proceso</span><strong>3</strong></div><div class="stat"><span>Abono despachado</span><strong>2.8 t</strong></div></div><h2>Módulos del sistema</h2><div class="modules">'+Object.keys(modules).filter(k=>k!=="Inicio").map(k=>'<div class="module"><div class="icon">'+modules[k].icon+'</div><span class="badge">'+rf[k]+'</span><h3>'+k+'</h3><p>'+modules[k].desc+'</p><button data-open="'+k+'">Abrir módulo →</button></div>').join("")+'</div><div class="activity"><h2>Actividad reciente</h2>'+activities.map(a=>'<div class="activity-row"><span class="time">'+a[0]+'</span><span>'+a[1]+'</span></div>').join("")+'</div>';bindOpen();}
function page(name){document.querySelectorAll("#nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===name));if(name==="Inicio"){home();return}let extra=name==="Mapa"?'<div class="map">📍 Mapa de fincas y puntos de recolección</div>':name==="Reportes"?'<div class="panel"><h3>Indicadores mensuales</h3><div class="bars"><div class="bar" style="height:55%"></div><div class="bar" style="height:75%"></div><div class="bar" style="height:45%"></div><div class="bar" style="height:90%"></div><div class="bar" style="height:65%"></div></div></div>':'<div class="panel"><h3>Registros</h3><p class="muted">'+modules[name].desc+'</p><table class="table"><tr><th>Registro</th><th>Estado</th><th>Detalle</th></tr><tr><td>L-2026-095</td><td><span class="badge">Activo</span></td><td>Finca El Progreso</td></tr><tr><td>L-2026-093</td><td><span class="badge">En proceso</span></td><td>Control operativo</td></tr><tr><td>L-2026-091</td><td><span class="badge">Completado</span></td><td>Registro histórico</td></tr></table></div>';content.innerHTML='<div class="eyebrow">'+modules[name].icon+" "+name+'</div><h1 class="title">'+name+'</h1><p class="muted">'+modules[name].desc+'</p>'+extra;}
function bindOpen(){document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>page(b.dataset.open));}
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>page(b.dataset.page));
document.getElementById("loginForm").onsubmit=e=>{e.preventDefault();if(document.getElementById("password").value.length<6)return;sessionStorage.setItem("bioLogged","1");document.getElementById("loginView").classList.add("hidden");document.getElementById("systemView").classList.remove("hidden");page("Inicio")};
document.getElementById("logout").onclick=()=>{sessionStorage.removeItem("bioLogged");location.reload()};
document.getElementById("collapse").onclick=()=>document.body.classList.toggle("collapsed");
if(sessionStorage.getItem("bioLogged")){document.getElementById("loginView").classList.add("hidden");document.getElementById("systemView").classList.remove("hidden");page("Inicio")}else{document.getElementById("loginView").classList.remove("hidden")}