CREATE DATABASE IF NOT EXISTS finca_catalina;
USE finca_catalina;

CREATE TABLE IF NOT EXISTS usuarios (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nombre VARCHAR(100) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lotes (
 id INT AUTO_INCREMENT PRIMARY KEY,
 codigo VARCHAR(50) NOT NULL UNIQUE,
 peso_bruto DECIMAL(10,2) NOT NULL,
 tara DECIMAL(10,2) NOT NULL,
 peso_neto DECIMAL(10,2) NOT NULL,
 tipo_biomasa VARCHAR(100) NOT NULL,
 estado VARCHAR(50) NOT NULL
);
